### ISSUE TITLE
Problems with UpdateAll for decimals

### ISSUE THREAD

**Issue by nathanbunn20** [RudeySH/EntityFramework.Utilities#13]
Hello, I'm reading in records that contain decimals (which were originally inserted using InsertAll), modifying some of the properties and using UpdateAll to save the records. The decimals on these records are being truncated in the hundredths place. This is happening to tens of thousands of records that I'm trying to update.

For example, say I have a record with the columns "Price" and "UpdateDate". The Price for this record is 9.9949 and UpdateDate is 10/1. The InsertAll correctly inserts the both Price and UpdateDate. However when I read in this record, perform some logic that only modifies the UpdateDate, and use UpdateAll (telling UpdateAll to update both Price and UpdateDate since the logic could have modified either columns), the Price gets saved as 9.9900. The same thing happens if the logic were to update the Price 10.8944. Using UpdateAll to update the record would cause this record's Price to save as 10.8900.

**Comment by RudeySH** [comment]
My first guess would be that EFUtilities doesn't understand which precision and scale it should use for your decimal column.

Are you using EF code-first or model-first? If so, could you try explicitly defining the precision and scale for the decimal property? I'm wondering if that solves your issue. Please see this SO post for information on how to do this in code-first:
https://stackoverflow.com/questions/3504660/decimal-precision-and-scale-in-ef-code-first

If you're using database-first you could double check to see if the code generated by EF understands which precision and scale is configured for your decimal column.

I'm also wondering this. When does the rounding occur? Could it be that after reading the values from the database (before updating), the values are already rounded at this point? I'm just guessing here.

Lastly, does the issue also occur when you save the records using EF's `SaveChanges` instead of `UpdateAll`?

If none of this helps, I'm probably going to need a zip of a new project that you can reproduce this issue with.

**Comment by nathanbunn20** [comment]
@RudeySH that did it! Specifying the precision for the columns in question in the code worked like a charm. The link you provided was great.

To answer your other questions, I'm using code first. EF's SaveChanges worked, but the job took 2+ minutes to run compared to ~8 seconds for UpdateAll. The rounding occurred during UpdateAll. My guess is that it has something to do with the temp table that the utility builds not knowing the precision of the decimal.

**Comment by RudeySH** [comment]
That's good to hear!

The temp table was definitely receiving the wrong precision or scale. It seems it assumes the wrong defaults when there's no precision or scale set in the code-first model.

I'll look into that later, because having to set a precision and scale shouldn't be a necessary thing.

**Comment by RudeySH** [comment]
I just did a simple test and determined that the default precision and scale that EF will use for a decimal is **(18,2)**. EFUtilities will automatically use these values when creating the temp table for `UpdateAll`.

If you weren't specifying a different precision and scale before my suggestion to do so, you shouldn't have been able to store values like `9.9949`. Either the decimals were being rounded at insert, or the precision and scale were set outside of your code-first model.

Perhaps the column was altered directly through SQL? Your numbers suggest you were using a scale of 4.

**Comment by nathanbunn20** [comment]
Yes in SQL I have the column set to decimal(19, 4). The insert was working prior to your suggestion, but update all was not. Now they both work by setting the precision with the model builder.

**Comment by RudeySH** [comment]
That explains a lot. When using code-first you should try to avoid altering things in SQL as much as possible. Things like max length, precision and scale should be set using the code-first data annotations or fluent API, so that libraries like EFUtilities know exactly what your database looks like.
